In [17]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [12]:
data = np.random.random((1000,100))
labels = np.random.randint(2,size=(1000,1))

In [32]:
model.get_weights()

[array([[-0.21087047, -0.06631017,  0.03380451, ..., -0.04508503,
          0.0889124 ,  0.10323408],
        [ 0.11271283,  0.15642223, -0.15650874, ..., -0.03629233,
         -0.00167549,  0.04741567],
        [-0.08505914, -0.12556139, -0.12926251, ..., -0.08695757,
          0.00275083,  0.15571243],
        ..., 
        [-0.09528304, -0.08575502, -0.01096441, ..., -0.06684206,
         -0.15356877,  0.00810562],
        [ 0.10542434, -0.16341998,  0.12402639, ..., -0.00869414,
         -0.0685197 , -0.03022869],
        [-0.15309268,  0.16663137, -0.16059656, ...,  0.085839  ,
         -0.1075479 , -0.10453703]], dtype=float32),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.], dtype=float32),
 array([[ 0.34645563],
        [ 0.18759167],
        [-0.33493805],
        [ 0.198232  ],
        [ 0.10629183],
        [ 0.13035828],
        [-0.275951

In [18]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])       

In [17]:
model.fit(data,labels,epochs=10,batch_size=32)   

Epoch 1/10
1000/1000 [==============================] - 0s - loss: 0.7157 - acc: 0.5070     
Epoch 2/10
1000/1000 [==============================] - 0s - loss: 0.6982 - acc: 0.5090     
Epoch 3/10
1000/1000 [==============================] - 0s - loss: 0.6917 - acc: 0.5290     
Epoch 4/10
1000/1000 [==============================] - 0s - loss: 0.6915 - acc: 0.5130     
Epoch 5/10
1000/1000 [==============================] - 0s - loss: 0.6877 - acc: 0.5350     
Epoch 6/10
1000/1000 [==============================] - 0s - loss: 0.6843 - acc: 0.5430     
Epoch 7/10
1000/1000 [==============================] - 0s - loss: 0.6798 - acc: 0.5690     
Epoch 8/10
1000/1000 [==============================] - 0s - loss: 0.6765 - acc: 0.5800     
Epoch 9/10
1000/1000 [==============================] - 0s - loss: 0.6743 - acc: 0.5790     
Epoch 10/10
1000/1000 [==============================] - 0s - loss: 0.6695 - acc: 0.5900     


In [18]:
predictions = model.predict(data)

In [20]:
type (predictions)

numpy.ndarray

In [1]:
from keras.datasets import boston_housing,mnist,cifar10,imdb
num_classes = 10

Using TensorFlow backend.


In [5]:
(x_train2,y_train2),(x_test2,y_test2) = boston_housing.load_data()
(x_train3,y_train3),(x_test3,y_test3) = cifar10.load_data()
(x_train4,y_train4),(x_test4,y_test4) = imdb.load_data()

In [14]:
x_train4[:5]

array([[   15,   256,     4, 31050,     7,  3766,     5,   723,    36,
           71,    43,   530,   476,    26,   400,   317,    46,     7,
            4, 12118,  1029,    13,   104,    88,     4,   381,    15,
          297,    98,    32,  2071,    56,    26,   141,     6,   194,
         7486,    18,     4,   226,    22,    21,   134,   476,    26,
          480,     5,   144,    30,  5535,    18,    51,    36,    28,
          224,    92,    25,   104,     4,   226,    65,    16,    38,
         1334,    88,    12,    16,   283,     5,    16,  4472,   113,
          103,    32,    15,    16,  5345,    19,   178,    32],
       [  125,    68, 23141,  6853,    15,   349,   165,  4362,    98,
            5,     4,   228,     9,    43, 36893,  1157,    15,   299,
          120,     5,   120,   174,    11,   220,   175,   136,    50,
            9,  4373,   228,  8255,     5, 25249,   656,   245,  2350,
            5,     4,  9837,   131,   152,   491,    18, 46151,    32,
         746

In [6]:
from keras.preprocessing import sequence
x_train4 = sequence.pad_sequences(x_train4,maxlen=80)
x_test4 = sequence.pad_sequences(x_test4,maxlen=80)

In [7]:
from keras.utils import to_categorical
Y_train3 = to_categorical(y_train3,num_classes)
Y_test3 = to_categorical(y_test3,num_classes)